# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=4.1.4
maven_group=com.yungnickyoung.minecraft.ribbits
archives_name=ribbits
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.10
# Dependencies
architectury_api_version=18.0.6
fabric_loader_version=0.17.3
fabric_api_version=0.136.0+1.21.10
neoforge_version=21.10.32-beta
geckolib_version=5.3-alpha-3
cloth_version=20.0.149
modmenu_version=16.0.0-rc.1