# Important Notes:
# Every field you add must be added to buildSrc/src/main/kotlin/multiloader-common.gradle.kts expandProps map.
# Project
version=4.1.4
group=com.yungnickyoung.minecraft.ribbits
java_version=25
# Common
minecraft_version=26.1.2
mod_name=Ribbits
common_mainclassname=Ribbits
fabric_mainclassname=RibbitsFabric
neoforge_mainclassname=RibbitsNeoForge
mod_author=Joosh, YUNGNICKYOUNG, Flechazo, HellionGames, Refresh Studios
mod_id=ribbits
license=LGPL-3.0
credits=
description=Adds cute little frogs to swamps!
minecraft_version_range=[26.1, 26.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1
# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.146.1+26.1.2
fabric_loader_version=0.18.4
# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.12-beta
neoforge_loader_version_range=[4,)
# Release Publishing
release_type=beta
# Valid values: client / server / both
release_dist=both
# Used by both Modrinth and CurseForge publishing tasks (supports multiline with \n)
release_changelog=
modrinth_project=
modrinth_project_fabric=
modrinth_project_neoforge=
curseforge_project=
curseforge_project_fabric=
curseforge_project_neoforge=
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
geckolib_version=5.5
cloth_version=26.1.154