# Project
version=4.1.2
java_version=21

# Metadata
mod_name=Ribbits
mod_full_name=Ribbits
mod_id=ribbits
# This is only for the JAR manifest. Full credits are included in the mods.toml and fabric.mod.json files.
mod_author=YUNGNICKYOUNG
mod_description=Adds cute little frogs to swamps!
mod_credits=Thank you to everyone who supported the official Ribbits plushie campaign!
license=LGPLv3
maven_group=com.yungnickyoung.minecraft.ribbits
mc_version=1.21.1
mc_version_range=[1.21, 1.22)
mc_version_range_fabric=>=1.21
parchment_minecraft=1.21
parchment_version=2024.06.23

# CurseForge/Modrinth Publishing
curseforgegradle_version=1.1.15
compatible_versions=1.21,1.21.1
curseforge_project_id=622967
modrinth_project_id=ribbits
debug_publish=true

# Common
yungsapi_version=5.1.5

# Fabric
fabric_version=0.102.0
fabric_loader_version=0.15.11
clothconfig_version_fabric=15.0.140
modmenu_version_fabric=11.0.2
geckolib_version_fabric=4.7.5.1

# NeoForge
neoforge_version=21.1.66
neoforge_version_range=[21.0.0,)
neoforge_loader_version_range=[4,)
geckolib_version_neoforge=4.7.5.1

# Credentials for publishing. Gets overwritten with global gradle.properties.
curseforgeApiKey=""
modrinthToken=""

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false